In [18]:
from dotenv import load_dotenv
import os
import pandas as pd
load_dotenv()
import pickle as pk
import numpy as np
from pathlib import Path
base_dir = os.getenv('BASEDIR')

from tqdm import tqdm
tqdm.pandas()

In [19]:
dataset='qanda'

In [20]:
import emoji

def extract_emojis(s):
    return([o['emoji'] for o in emoji.emoji_list(s)])

In [21]:
dataset_name='qanda'
data = pd.read_csv(os.path.join(base_dir,'data','01_raw_data','qanda','qanda_emoji.csv'), dtype=str, names=['tid', 'rid' ,'qid', 'uid','name', 'bio', 'date', 'text_extended', 'text', 'hashtags', 'hashtags_extended', 'mentions', 'mentions_extended', 'urls_extended', 'urls'], index_col=False)

data['text'] = data['text'].fillna('')
data['bio'] = data['bio'].fillna('')
data['name'] = data['name'].fillna('')

In [25]:
data

,tid,rid,qid,uid,name,bio,date,text_extended,text,hashtags,hashtags_extended,mentions,mentions_extended,urls_extended,urls
0,uid,NaN,0,NaN,,,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
1,1000001245946490880,0,['‚Ñ¢Ô∏è'],NaN,,,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
2,1000022700092411904,0,[],NaN,,,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
3,1000111986917572608,0,['ü§î'],NaN,,,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
4,1000127207048728576,0,[],NaN,,,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103070,999931831364435968,0,['‚ú®'],NaN,,,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
103071,999937171766235136,0,['üòÇ'],NaN,,,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
103072,999954234119356416,0,"['‚ù§Ô∏è', 'üíß', 'üê®', 'üç£']",NaN,,,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
103073,999960633960316929,0,[],NaN,,,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN
103074,999968158231363585,0,[],NaN,,,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
data_per_user = data.groupby('uid').progress_apply(lambda d: pd.DataFrame({'name' : [d['name'].values[0]], 'bio' : [d['bio'].values[0]], 'text' : [' '.join(d['text'])] }))

0it [00:00, ?it/s]

In [23]:
emojis = data_per_user.progress_apply(lambda row: extract_emojis(row['name'] + row['bio'] + row['text']), axis=1)

1it [00:00, 1004.62it/s]

In [24]:
count_aus_flag = emojis.progress_apply(lambda l: len([x for x in l if x == 'üá¶üá∫']))

/data/roram/anaconda3/envs/rr/lib/python3.10/site-packages/tqdm/std.py:775: RuntimeWarning: divide by zero encountered in long_scalars
  total = df.size // df.shape[axis]
2it [00:00, 2966.27it/s]

array([0, 1])

In [11]:
emojis.to_csv(os.path.join(base_dir,'data','01_raw_data',dataset_name,'flag_count.csv'))